# name of author
name: Krishna Mahato
# college registeration number
regdno: 2041013021
# github username
github: krishna9304
# set number (1/2/3)
set: 1
# problem statement number (1/2/3/4)
question: 1
# description of the project
description: The project is hosted on vercel and the link is https://shop-town.vercel.app/ and the project is made with ReactJS , Redux for frontend, firebase for backend and MAPBOX for Map API.
# credits of project
credits: Google, Github, Vercel, Mapbox
